
JOINED_SERVER = "JOIN_NEW_SERVER"
DISCONNECT_SERVER = "DISCONNECT_SERVER"
GET_CLUSTER = "GET_CLUSTER_SERVER"
RESP_CLUSTER = "RESP_CLUSTER_SERVER"

# TYPE
CMD = "CMD"
PUBLISH = "PUBLISH"
BROADCAST = "BROADCAST"